### ISSUE TITLE
Yaml not valid

### ISSUE THREAD

**Issue by Sirhexalot** [hubtub2/ha_custom_components#1]
Hi,

I tried your wonderfull Code.

But when I add 

- platform: eta_heating
host: 192.168.178.75
port: 8080
scan_interval: 60 to  configuration.yaml:

HA wont start anymore.

**Comment by zypro** [comment]
Did you activate the webservice and copy the eta folder of the this repo to /config/custom_components/ ?

Restarting ha wasnt helping?

**Comment by zypro** [comment]
Ah, maybe you missed, that you need copy the platform Part in the Sensors section (which may not exist yet) in the configuration.yaml.

It needs to be:

```
sensor:
  - platform: eta_heating
   ... 
```

**Comment by Sirhexalot** [comment]
Ok thanks. I try it this evening

**Comment by Sirhexalot** [comment]
Validate your configuration if you recently made some changes to it and want to make sure that it is all valid.
Configuration invalid!

Platform error sensor.eta_heating - Integration 'eta_heating' not found.

**Comment by zypro** [comment]
Can you share your sensor part of the configuration.yaml?

What's the full path of the location where you copied the `eta` folder to?
Did you restart ha after the config change?

**Comment by Sirhexalot** [comment]
Thanks a lot!!!!!

/config/custom-components/eta


# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor:
  - platform: eta_heating
    host: 192.168.178.105
    port: 8080
    scan_interval: 60

**Comment by zypro** [comment]
It should be `/config/custom_components/eta/` (underscore not minus).

Be aware of the right indention (sensor has to be on the same level like `tts:`):
```
default_config:

sensor:
  - platform: eta_heating
    host: 192.168.178.75
    port: 8080
    scan_interval: 60

# Text to speech
tts:
  - platform: google_translate
```

P.S. have a look at markdown to format your code ;-) https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code

**Comment by Sirhexalot** [comment]
You are the best! Now it works thanks a lot!

**Comment by zypro** [comment]
then close the issue and have fun. I am gonna push some PRs soon to improve the Code.

**Comment by hubtub2** [comment]
Thanks fo helping, closing.
